export const STORIES_LIST_FETCH = "STORIES_LIST_FETCH";
export const STORIES_LIST_REQUEST = "STORIES_LIST_REQUEST";
export const STORIES_LIST_SUCCESS = "STORIES_LIST_SUCCESS";
export const STORIES_LIST_FAIL = "STORIES_LIST_FAIL";
export const JOBS_LIST_FETCH = "JOBS_LIST_FETCH";
export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";